name: project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  percent_indicator: ^4.2.3
  country_picker: ^2.0.20
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0


flutter_icons:
  ios: true
  android: true
  image_path: 'assets/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
